### ISSUE TITLE
Delete Multiple View (feature)

### ISSUE THREAD

**Issue by rtpm** [brack3t/django-braces#1]
There are many requests on the web for DeleteMultiple mixin which would let users delete objects from ListView View by selecting checkboxes. Couldn't find one on the net and as I see some users use forms with MultipleSelect.. and others use request.POST.getlist().

Think this would be a great feature.

**Comment by niteshrawat1995** [comment]
@rtpm , Thanks for raising this issue, I really something like this. Did anyone find a solution to this ? If yes, please share! thanks in advance :)
