### ISSUE TITLE
How do you actually use post_ajax()?

### ISSUE THREAD

**Issue by AntelopeSalad** [brack3t/django-braces#100]
There's no documentation on this and there are no tests that I saw. There's also no hits on Google or SO and no one knows on IRC.

How would you convert this to using braces?
https://docs.djangoproject.com/en/1.6/topics/class-based-views/generic-editing/#ajax-example

If I do something like this:

```
class FooCreate(AjaxResponseMixin, CreateView):
    model = Foo
    success_url = reverse_lazy('foos:list')

    def post_ajax(self, request, *args, **kwargs):
        data = {
            'foo': {
                'pk': self.object.pk,
                'first_name': self.object.first_name,
                'last_name': self.object.last_name,
            },
        }

        return self.render(request, "foos/_as_single_tr.html", data)
```

Then it crashes saying self.object does not exist.

**Comment by Joshua-Swain** [comment]
Can we get a link to some of that Ajax Response documentation?
