### ISSUE TITLE
SSLRequiredMixin

### ISSUE THREAD

**Issue by bnice5000** [brack3t/django-braces#108]
I would like to request that an SSLRequiredMixin be created.  I have the basics of one right now.  It is a modification of  https://gist.github.com/drewtempelmeyer/4669799.  However, I am not sure if this is a good idea or even secure.  It does work.  I figured that if it was in the Braces package it would be more likely to get attention from people who know what's up.  Code below:

```
class SSLRequiredMixin(object):

    def dispatch(self, request, *args, **kwargs):
        # SSL, Debug, and Post don't mix!
        if not settings.DEBUG and not request.is_secure():
            host = request.get_host()
            url = 'https://{0}{1}'.format(host, request.get_full_path())
            return redirect(url)
        return super(SSLRequiredMixin, self).dispatch(request, *args, **kwargs)
```

**Comment by chrisjones-brack3t** [comment]
Done
