### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by mikebryant** [brack3t/django-braces#155]
Can we get a new official release?
In my package I need to be able to depend on a released version with the redirect_unauthenticated_users feature

**Comment by scottwoodall** [comment]
Regarding @mikebryant comment about any blocking issues that need help fixing? I was thinking a new release would happen since this issue was closed but I don't see one.

How can we help out to get a new release cut?

**Comment by scottwoodall** [comment]
Regarding @mikebryant comment about any blocking issues that need help fixing? I was thinking a new release would happen since this issue was closed but I don't see one.

How can we help out to get a new release cut?
