### ISSUE TITLE
object has no attribute 'request_json'

### ISSUE THREAD

**Issue by shiroming** [brack3t/django-braces#165]
I have import 
from braces.views import JSONResponseMixin, AjaxResponseMixin, JsonRequestResponseMixin,CsrfExemptMixin
from django.views.generic import View
It is also an error 500,object has no attribute 'request_json'

**Comment by kennethlove** [comment]
Can you provide more context? It's hard to debug a view we can't actually see.

**Comment by shiroming** [comment]
I found it, import in the wrong order.
