### ISSUE TITLE
Django 1.8 Support

### ISSUE THREAD

**Issue by chrisjones-brack3t** [brack3t/django-braces#168]
Need to add in testing for Django 1.8 for both Python 2.7 & Python 3.3/3.4. I'd also like to bump the version numbers to follow along with Django's versions. Instead of a 1.5 release, I'd rather jump to 1.8 with fixes being points releases, e.g. 1.8.1, 1.8.2.

@kennethlove Thoughts?

**Comment by kennethlove** [comment]
I'm good with both of those suggestions

------------------

**Comment by chrisjones-brack3t** [comment]
@kennethlove We should probably also follow along with Django's supported releases. We're still testing all the way back to Django 1.4. If you look at the docs for anything below Django 1.7 they have a banner at the top saying it's not a supported release and to upgrade.

**Comment by kennethlove** [comment]
No problems with dropping support for 1.4 but we should just do it organically as we add or improve features. No reason to do any rewrites for it at this point. 

------------------
