### ISSUE TITLE
Invalid package uploaded to Pypi for 1.8

### ISSUE THREAD

**Issue by nikdoof** [brack3t/django-braces#174]
https://pypi.python.org/pypi/django-braces/

A file called "django-braces-1.8.0.macosx-10.9-x86_64.tar.gz " has been uploaded to Pypi, that doesn't seem to contain django-braces at all. Older setuptools seem to be preferring this package.

**Comment by chrisjones-brack3t** [comment]
Not sure how that happened. I removed the "dumb" binary. Mind giving it another try now? If that doesn't solve the problem we'll just roll out a new release.
