### ISSUE TITLE
Redirect loop UserPassesTestMixin

### ISSUE THREAD

**Issue by cdvv7788** [brack3t/django-braces#189]
When i return False and user is logged in, it is entering a redirect loop with the login page

**Comment by chrisjones-brack3t** [comment]
Can you provide a code example that reproduces the problem?

**Comment by cdvv7788** [comment]
from django.views import TemplateView

from braces.views import UserPassesTestMixin


class SomeUserPassView(UserPassesTestMixin, TemplateView):
    def test_func(self, user):
        return (some condition evaluated)

I am just following the docs to try this one.

**Comment by cdvv7788** [comment]
Overriding no_permissions_fail() and setting my redirects explicitly there fixed this issue, at least for me. By default it is redirecting to login_url (as any other child of AccessMixin).

```python
def no_permissions_fail(self, request=None):
        if request.user.is_authenticated():
            messages.add_message(request, messages.ERROR, 'Some error.')
            return redirect(reverse('some_url'))
        else:
            return super(SomeUserPassView, self).no_permissions_fail(request)
```

**Comment by chrisjones-brack3t** [comment]
I was going to suggest overriding `no_permissions_fail`. I just noticed in the documentation there is no mention of this method and no examples. I'll add an issue to add docs for that.
