### ISSUE TITLE
OrderableListMixin docs 

### ISSUE THREAD

**Issue by epicserve** [brack3t/django-braces#191]
So I was reading the docs for [OrderableListMixin](http://django-braces.readthedocs.org/en/latest/other.html#orderablelistmixin) and I wasn't seeing anything about it adding anything to the context_data with variables for order_by and ordering. I just checked the source code however and it looks like the mixin does add to the context, so is this just an oversight as to the reason it's not in the docs? If so, would you like me to give you a pull request with that info in the docs?

**Comment by kennethlove** [comment]
Always submit a PR :smile_cat:

**Comment by epicserve** [comment]
Would it be good to include an example of how you might use this information if you're using something like bootstrap or is that overkill?

**Comment by kennethlove** [comment]
Sure, so long as the example isn't ridiculously over-blown.

**Comment by chrisjones-brack3t** [comment]
closing very old issues
