### ISSUE TITLE
Add CurrentAppMixin

### ISSUE THREAD

**Issue by georgema1982** [brack3t/django-braces#197]
I wonder if there's already a mixin that adds current_app attribute to request in Django 1.8+ and to template context before version 1.8.

The issue is that to write reusable apps that can be deployed multiple times in one project, current_app attribute needs to be set to request or template context depending on Django version so that url tag in template can correctly resolve to the url of current app. The topic is covered here: https://docs.djangoproject.com/en/1.8/topics/http/urls/#reversing-namespaced-urls.

The Django document has already provided the solution such mixin needs. Just override render_to_response function to look like:

```
def render_to_response(self, context, **response_kwargs):
    self.request.current_app = self.request.resolver_match.namespace
    response_kwargs['current_app'] = self.request.resolver_match.namespace
    return super(DetailView, self).render_to_response(context, **response_kwargs)
```

**Comment by chrisjones-brack3t** [comment]
closing very old issues
