### ISSUE TITLE
Allow desc ordering as a default option in the OrderableListMixin

### ISSUE THREAD

**Issue by hanneshapke** [brack3t/django-braces#199]
I found a need to change the default ordering in the `OrderableListMixin` from `asc` to `desc`, but I couldn't find a clean way of doing it. Maybe it missed a very simple solution.

Instead I have created a PR (#198) to set the `ordering_default`. If it is `None`, `asc` is assumed and the Mixin behaves as usual. If `ordering_default` is set to `desc`, and no query param given, the order will be reversed.

Tests and docs are updated.

**Comment by patrickbeeson** [comment]
+1

**Comment by panizza** [comment]
+1

**Comment by chrisjones-brack3t** [comment]
closing very old issues
