### ISSUE TITLE
Access mixins should have a uniform validation/checking function

### ISSUE THREAD

**Issue by georgema1982** [brack3t/django-braces#205]
This is a code refactoring suggestion rather than a bug. My problem with current access minxins is that they have boilerplate codes in dispatch function like below:

```
    if not passed: #passed is whatever condition checking result
        if self.raise_exception:
            raise PermissionDenied
        else:
            return redirect_to_login(request.get_full_path(),
                                     self.get_login_url(),
                                     self.get_redirect_field_name())
```

In my opinion, these mixins should derive from a base mixin that has a dispatch function that would call a test/validation function. Each access mixin should only override the test/validation function and the dispatch function would handle the boilerplate codes.

**Comment by chrisjones-brack3t** [comment]
closing very old issues
