### ISSUE TITLE
StaffuserRequiredMixin error

### ISSUE THREAD

**Issue by LABETE** [brack3t/django-braces#206]
Hi, I was trying to use the StaffuserRequiredMixin as in the example in the documentation

class SomeStaffuserView(views.LoginRequiredMixin, views.StaffuserRequiredMixin, TemplateView):

but when I try to load the page with a user without staff authorization I am getting this error: ERR_TOO_MANY_REDIRECTS

Apparently the site is trying to redirect me to the login page but I am logged in as a normal user. I am using django-allauth.

**Comment by kennethlove** [comment]
This should have been fixed in the 1.9.0 release. Closing this for now. Reopen if it's still an issue.

**Comment by paramono** [comment]
I am currently experiencing exactly the same issue.

django==1.11.6
django-braces==1.11.0
django-allauth==0.33.0

**Comment by kennethlove** [comment]
I'll look into stuff and get a new release out soon

**Comment by hobbyhack** [comment]
In case someone finds this....  Braces defaults to sending people to login when a permission is denied.  The next querystring identifies where they were trying to go.  Allauth sends a logged in user to the url in the "next" querystring.  So this just loops through redirecting to login with a "next" query string that is used to redirect the user back to the page they tried to access if they are already logged in. Eventually the user will get a too many redirects error.

Braces provides some settings to deal with this situation:  https://django-braces.readthedocs.io/en/latest/access.html

Including the following in the view definition raises permission denied which is what I wanted in this case:
`raise_exception = True`
