### ISSUE TITLE
Include this `ParentObjectMixin` class?

### ISSUE THREAD

**Issue by vdboor** [brack3t/django-braces#210]
Hi! I've written a `ParentObjectMixin` class, which mimicks the `SingleObjectMixin`, but allows for having a parent object that filters the queryset. This allows features such as:
- selecting a "post" in a "category"
- showing a partial listing based on a parent.

Would you like to have a pull request for this?

**Comment by kennethlove** [comment]
Sure, submit a PR?

**Comment by chrisjones-brack3t** [comment]
closing very old issues
