### ISSUE TITLE
Apps not ready error when importing before models are loaded

### ISSUE THREAD

**Issue by Pawamoy** [brack3t/django-braces#219]
If you import `from braces.views import AjaxResponseMixin, JSONResponseMixin` before your models are loaded, it will result in an "Apps are not ready" Django error.

See an example in https://github.com/Pawamoy/django-suit-dashboard/issues/30.

It this something intentional or something that could be avoided?

**Comment by kennethlove** [comment]
That would be an implementation detail that django-braces shouldn't concern itself with. Properly loading your apps is a concern of your project, not something we can really watch out for.
