### ISSUE TITLE
Three database queries in CanonicalSlugDetailMixin

### ISSUE THREAD

**Issue by leon-matthews** [brack3t/django-braces#225]
I have a simple ProductDetailView, where I'm seeing three queries instead of the expected one, only when using _CanonicalSlugDetailMixin_ - at least according to _django-debug-toolbar_.

In the SQL tab of the debug toolbar I see the expected single call to `SELECT ••• FROM "products_product" WHERE "products_product"."id" = '1'` when not using the mixin, but that query is duplicated three times just as soon as the mixin is added to my detail view, in the following locations:

1. _braces/views/_other.py in dispatch(79)_  `obj = self.get_object()`
2. _braces/views/_other.py in get_canonical_slug(111)_ `return self.get_object().slug`
3.  _braces/views/_other.py in dispatch(101)_  `request, *args, **kwargs)`

I'm running _django-braces 1.11.0_, _Django 1.11.3_, and _Debug Toolbar 1.8_.

**Comment by chrisjones-brack3t** [comment]
closing very old issues
