### ISSUE TITLE
Support for Django 1.11?

### ISSUE THREAD

**Issue by brylie** [brack3t/django-braces#226]
The Cookiecutter Django project depends on this package. Currently, Cookiecutter Django is pinned to Django 1.10.x, based on an [issue to check for 1.11.x support in project dependencies](https://github.com/pydanny/cookiecutter-django/issues/1111). 

Does the django-braces package support Django 1.11?

**Comment by kennethlove** [comment]
Yeah, django-braces should be 100% compatible with all future Django releases unless they restructure how CBVs are constructed.
