### ISSUE TITLE
Using GroupRequiredMixin while a user's role/group can be different according to the project he/she is working on?

### ISSUE THREAD

**Issue by lhoupert** [brack3t/django-braces#267]
Hi ! It may not be the appropriate place to post this issue but I thought I would try :-) 

I would appreciate comments/help on this. 

I would like to control the views seen by a user according to its role. However the user's role can be different according to which project he/she is working on... 

I am happy to use Django groups nut I thought a multiple user type model could be more appropriate ... along the lines of [this video](https://www.youtube.com/watch?v=f0hdXr2MOEA)  where @pydanny  is using Django [Proxy Models](https://docs.djangoproject.com/en/3.0/topics/db/models/#proxy-models).

## Situation

I have a list of XX projects (`proj01`, `proj02` , `projXX`, ...).
All these projects have their specific page that can be accessed through a specific url `mysite/projXX/`  

I have multiple users: Adam, Bob, Caroline, Dany, Ed, ...

Each user can have several roles according to the project they are working on (e.g. manager, developer, documentarist, reviewer, editor, ...)

A user can have a different role according to the project. E.g. Adam can be reviewer on proj01 but editor on proj02 while Bob can be editor on proj01 but reviewer on proj02, etc..

I started defining multiple user types in the `models.py` file below (only reviewer and editor roles):

```python
# accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


class User(AbstractUser):
    class Types(models.TextChoices):
        EDITOR= "EDITOR", "Editor"
        REVIEWER = "REVIEWER", "Reviewer"

    base_type = Types.EDITOR

    type = models.CharField(
        _("Type"), max_length=50, choices=Types.choices, default=base_type
    )

    name = models.CharField(_("Name of User"), blank=True, max_length=255)

    def get_absolute_url(self):
        return reverse("users:detail", kwargs={"username": self.username})

    def save(self, *args, **kwargs):
        if not self.id:
            self.type = self.base_type
        return super().save(*args, **kwargs)


class EditorManager(models.Manager):
    def get_queryset(self, *args, **kwargs):
        return super().get_queryset(*args, **kwargs).filter(type=User.Types.EDITOR)


class ReviewerManager(models.Manager):
    def get_queryset(self, *args, **kwargs):
        return super().get_queryset(*args, **kwargs).filter(type=User.Types.REVIEWER)


class EditorMore(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    gadgets = models.TextField()


class Editor(User):
    base_type = User.Types.EDITOR
    objects = EditorManager()

    class Meta:
        proxy = True

    def edit(self):
        return "Edition in progress"


class ReviewerMore(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    model = models.CharField(max_length=255)
    make = models.CharField(max_length=255)
    year = models.IntegerField()


class Reviewer(User):
    base_type = User.Types.REVIEWER
    objects = ReviewerManager()

    @property
    def more(self):
        return self.reviewermore

    class Meta:
        proxy = True

    def review(self):
        return "In Review" 
```

## Question: 

What is the best way to handle the fact that the role of the user can change according to the project page he/she is visiting?

Example: If Adam is logged in and visits the page `mysite/proj01/` I would like him to access only the content allowed for a reviewer while if Adam visit  `mysite/proj02/`, I would like the user to see only the content allowed to the editor.
 
Ideally, I would like each user to have its unique entry in the user database. I was thinking that the project-dependent role level could be stored as a dictionary? For example: 
```python
{'proj01':'reviewer', 'proj02':'editor', 'projxx': 'roleY', ... } 
```

How would you django-braces to tackle this problem?  
I opened a Stackoverflow post about this [here](https://stackoverflow.com/questions/68168037/how-to-implement-django-multiple-user-types-while-one-user-can-have-different-r)

**Comment by chrisjones-brack3t** [comment]
Looks like your SO post has an accepted answer. Closing.
