### ISSUE TITLE
New release with support for django 3.2

### ISSUE THREAD

**Issue by magajh** [brack3t/django-braces#268]
Hi @kennethlove @chrisjones-brack3t!

The edX project is looking forward to using django-braces with Django 3.2. Here is the associated Github issue https://github.com/edx/upgrades/issues/23

I noticed that PR #265  added support for Django 3.2.
Are there any chances this PR could get reviewed and merged so a new version can be released anytime soon? I would be happy to help in case there are any blockers with this.

Thank you in advance!

**Comment by kennethlove** [comment]
Hi, sorry, yes, we've been meaning to go over several PRs lately but just
have not had time yet.

**Comment by chrisjones-brack3t** [comment]
Should have a release out today. 👍🏻
