### ISSUE TITLE
Travis CI - end of a era

### ISSUE THREAD

**Issue by richardbarran** [brack3t/django-braces#271]
This project currently uses Travis CI - however the "free plans" on Travis are being phased out.
Lots of other open source projects are migrating to Github Actions. If I submitted a PR for switching to Github Actions would it be something that would of interest?

**Comment by kennethlove** [comment]
@richardbarran of course! We don't have a ton of experience with CI setup on our own so any help is welcome

**Comment by kennethlove** [comment]
We've moved CI to Github Actions so I'm closing this ticket
