### ISSUE TITLE
django-braces looks old

### ISSUE THREAD

**Issue by kennethlove** [brack3t/django-braces#276]
We wrote this back when 2.7 was in its heyday, Django CBVs had barely dropped. It was a different world. We need to bring this repo to modern Python.

**Comment by auvipy** [comment]
how can contributors help?

**Comment by kennethlove** [comment]
@auvipy helping us get to 100% test coverage would probably be the best first step after I finish my modernization pass.

**Comment by auvipy** [comment]
ok. + dropping the python 2 compat codes as well? you can assign me
