### ISSUE TITLE
Potential mixin contributions - sortable-listview & spreadsheet-response

### ISSUE THREAD

**Issue by birdsarah** [brack3t/django-braces#75]
Hi lovely django-braces people, hope this is the right place for this, I wasn't sure how best to reach you otherwise. Am a huge fan of braces, use it a lot.

I have two mixins which I'm wondering whether you might be interested in. If so, I'd be delighted to do the work to get them fit for braces, they already have some tests, but not python 3 etc.. 

**django-spreadsheetresponsemixin** - https://github.com/birdsarah/django-spreadsheetresponsemixin
Renders views that have a queryset e.g. a ListView, into an excel spreadsheet or a CSV. Takes headers from model or you can customize them. Can specify fields and order columns by doing so. Maybe you don't want to rely on additional libraries, so maybe just the CSV portion would be interesting.

**django-sortable-listview** - https://github.com/aptivate/django-sortable-listview
Like OrderableListMixin but takes things a bit further, for example, if you're already sorted in one direction it'll provide context data so that the next sort can be in the opposite direction. Obviously, would be happy to pull out specific features and add them to the existing OrderableListMixin.

Thanks in advance for your thoughts.

**Comment by chrisjones-brack3t** [comment]
Old issue. If anyone is interested in making this happen a PR would be awesome.

**Comment by birdsarah** [comment]
Ugh - can't believe this is coming up on two years :s Thanks for closing it. Will certainly open a new PR when my backlog and ambition are a little more in sync!
